class TestData:
    FIRST_NAME = 'John'
    LAST_NAME = 'Richardson'
    EMAIL = 'john.richardson@yahoo.com'
    GENDER = 'Male'
    MOBILE_PHONE = '9999999999'
    DAY_OF_BIRTH = '20'
    MONTH_OF_BIRTH = '10'  # November
    YEAR_OF_BIRTH = '1965'
    SUBJECT_MATHS = 'Maths'
    SUBJECT_ENGLISH = 'English'
    HOBBY_READING = 'Reading'
    HOBBY_MUSIC = 'Music'
    CURRENT_ADDRESS = 'USA, New-York, 15 ave. 17'
    STATE = 'NCR'
    CITY = 'Noida'
